---
title: "Quiz 2"
author: "Amy Su Jiang"
output: html_document
---
<style>answer {color: coral; font-size:0.9em; }</style><br />

### Question 1

Which of the following commands will create a directory called data in your current working directory? 

    pwd ../data 
    
    mkdir data 
    
    mkdir /Users/data 
    
    touch data 

<pre><answer>mkdir data </answer></pre><br />  


### Question 2

Which of the following will initiate a git repository locally?

    git merge origin master 
    
    git pull 
    
    git init 
    
    git merge 

<pre><answer>git init</answer></pre><br />  


### Question 3

Suppose you have forked a repository called datascientist on Github but it isn't on your local computer yet. Which of the following is the command to bring the directory to your local computer? (For this question assume that your user name is username)

    git clone https://github.com/username/datascientist.git 
    
    git pull 
    
    git pull datascientist master 
    
    git pull https://github.com/username/datascientist.git 

<pre><answer>git clone https://github.com/username/datascientist.git</answer></pre><br />  


### Question 4

Which of the following will create a markdown document with a secondary heading saying "Data Science Specialization" and an unordered list with the following for bullet points: Uses R, Nine courses, Goes from raw data to data products

    ### Data Science Specialization 
    
    * Uses R 
    * Nine courses 
    * Goes from raw data to data products 
    
    *** Data Science Specialization 
    
    * Uses R 
    * Nine courses 
    * Goes from raw data to data products 
    
    ## Data Science Specialization 
    
    li Uses R 
    li Nine courses 
    li Goes from raw data to data products 
    
    ## Data Science Specialization 
    
    * Uses R 
    * Nine courses 
    * Goes from raw data to data products 
    
    *h2 Data Science Specialization 
    
    * Uses R 
    * Nine courses 
    * Goes from raw data to data products 

<pre><answer>## Data Science Specialization 

* Uses R 
* Nine courses 
* Goes from raw data to data products 
</answer></pre><br />  


### Question 5

Install and load the KernSmooth R package. What does the copyright message say? 

    Copyright M. P. Wand 1997-2013 
    
    Copyright M. P. Wand 1990-2009 
    
    Copyright KernSmooth 1997-2009 
    
    Copyright M. P. Wand 1997-2009 

<pre><answer>Copyright M. P. Wand 1997-2009</answer></pre><br />  








