---
title: "Quiz 1"
author: "Amy Su Jiang"
output: html_document
---
<style>answer {color: coral; font-size:0.9em; }</style><br />

### Question 1

Which of the following are courses in the Data Science Specialization? Select all that apply.

    Regression Models
    Exploratory Data Analysis
    Data Science 101
    The Elements of Statistical Learning

<pre><answer>Regression Models
Exploratory Data Analysis</answer></pre><br />

### Question 2

Why are we using R for the course track? Select all that apply.

    R has a large number of add on packages that are useful for data analysis.
    R has a nice IDE, Rstudio.
    R is a general purpose programming language.
    R is the only programming language data scientists use.

<pre><answer>R has a large number of add on packages that are useful for data analysis.
R has a nice IDE, Rstudio.   </answer></pre><br />

### Question 3

What are good ways to find answers to questions in this course track? Select all that apply.

    Emailing the community TAs
    Emailing your instructors
    Looking through R help files.
    Searching Stack Overflow

<pre><answer>Searching Stack Overflow
Looking through R help files.</answer></pre><br />

### Question 4

What are characteristics of good questions on the message boards? Select all that apply.

    Explicitly lists versions of software being used.
    Asks for a code fix without explanation.
    Is an exact homework question.
    Is polite and courteous.

<pre><answer>Explicitly lists versions of software being used.
Is polite and courteous.</answer></pre><br />

### Question 5

Which of the following packages provides machine learning functionality? Select all that apply

    gbm
    lubridate
    knitr
    caret

<pre><answer>gbm
caret</answer></pre><br />
